source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Test_Engie_SE_iOS' do

  pod 'NVActivityIndicatorView', "3.0"
  pod 'AFNetworking', '~> 3.0'  
end

target 'Test_Engie_SE_iOSTests' do

end

